prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix cc: <http://creativecommons.org/ns#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix occult: <http://data.totl.net/occult/>
prefix planet: <http://data.totl.net/planet/>
prefix element: <http://data.totl.net/element/>
prefix zodiac: <http://data.totl.net/zodiac/ontology/>

# List all zodiac signs assiated with the element "Air"

SELECT ?name ?desc WHERE 
  { ?s occult:correspondsTo element:Air 
     ; foaf:name ?name
     ; dcterms:description ?desc
  }

